### ISSUE TITLE
Problem with addresses with slash 

### ISSUE THREAD

**Issue by philippseemann** [VIISON/AddressSplitting#15]
A customer address with a slash leads to a wrong address splitting. The part after the slash is moved to the additional address line.

An example for the address is: `Reitelbauerstr. 7 1/2`

![image](https://user-images.githubusercontent.com/16401785/32948549-eaf07bb8-cb9f-11e7-9ea0-b62827c5adf7.png)

![image](https://user-images.githubusercontent.com/16401785/32948482-a1204e46-cb9f-11e7-9e87-171b0b59d3be.png)

This problem is reproducable.

**Comment by adizdar** [comment]
Because more People are asking/complaining about this, it will be prioritized.

**Comment by windaishi** [comment]
I did a pull request for this: https://github.com/VIISON/AddressSplitting/pull/16
I am waiting for review and merge. After that, we have to update every shipping adapter :(

**Comment by windaishi** [comment]
Merged.
