### ISSUE TITLE
Problem with addresses with more than one slash

### ISSUE THREAD

**Issue by maximilianoster** [VIISON/AddressSplitting#17]
After we fixed the behavior of the address splitter for addresses with one slash in it (https://github.com/VIISON/AddressSplitting/issues/15), we now have the same problem for addresses with two slashes...

![image](https://user-images.githubusercontent.com/15085275/36159943-47eabad8-10e0-11e8-972d-0e5a9c8ea247.png)

![image](https://user-images.githubusercontent.com/15085275/36160022-79851d40-10e0-11e8-9fc2-aa9d0cf07710.png)

The problem is reported primarily by Austrian users, since the house number is often described as "Hausnummer/Tür/Stiege" in Austria. They currently have the problem that the parcels cannot be delivered due to this and another attempt at delivery after manual address correction is necessary.

**Comment by maximilianzachow** [comment]
Candle-Dream <info@candle-dream.de> reported the same problem in mail 16193d5daf61a259 and wants to be informed once a fix is available. In the reported issue the address also had two slashes in it.

**Comment by windaishi** [comment]
I tried to add support for this address format, but did not success. No matter how I try to add the support for Austrian addresses, I break the splitter for other address formats. See this branch for example: https://github.com/VIISON/AddressSplitting/tree/windaishi/improve-support-of-austrian-addresses
For example the following address format would not be corretly splitted anymore: "Karlstr. 1 c/o Breitner"

**Comment by windaishi** [comment]
The Address Splitter  v0.3.2  has been released and now includes improved support for Austrian addresses. I am going to update this in ShippingCommon.
