### ISSUE TITLE
Get rid of AddressSplittingException, use SPL Exceptions instead

### ISSUE THREAD

**Issue by bcremer** [VIISON/AddressSplitting#2]
I would like to see the unnecessary `AddressSplittingException` exception replaced by the more semantic SPL-Exceptions [`InvalidArgumentException`](http://php.net/manual/en/class.invalidargumentexception.php) and [`RuntimeException`](http://php.net/manual/en/class.runtimeexception.php).

```php
$result = preg_match($regex, $address, $matches);
if ($result === 0) {
    throw new \InvalidArgumentException(sprintf('Address % could not be splitted into street name and house number', $address));
} elseif ($result === false) {
    throw new \RuntimeException(sprintf('Error occured while trying to split address %s', $address));
}
```

**Comment by andrewisplinghoff** [comment]
Good idea, this was merged in https://github.com/VIISON/AddressSplitting/commit/70991b7c3288decca611033e9a1ab5517f2fd923.
